apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seasidefm
  name: heat-level
  labels:
    app: botsuro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heat-level
  template:
    metadata:
      labels:
        app: heat-level
    spec:
      containers:
        - name: heat-level
          # Add your own personal registry here
          image: registry.dougflynn.dev/heat-level:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: heat-level-secret
                  key: MONGO_URL
      imagePullSecrets:
        - name: regcred